project:
  type: website
  output-dir: docs

website:
  title: "Juluis Foyet"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - text: Publications
        href: pubs.qmd

format:
  html:
    theme: cyborg
    css: styles.css
    toc: true



