---
title: "Publications"
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, results='asis', echo=FALSE, message=FALSE, warning=FALSE}
library(htmltools)
library(dplyr)
library(readr)

pub.data <- read_csv("academic_dataset.csv") |> 
  filter(status == "Published")


years <- unique(pub.data$year) |> sort(decreasing = T)
for(k in years){
  cat(paste0(h1(k)))
  
  pub.in <- pub.data |> 
    filter(year == k) |> 
    arrange(-SN)
  
  for(type in unique(pub.in$type_of_publication)){
    cat(paste0(h4(type)))
    
    pub.k <- pub.in |> filter(type_of_publication == type)
    
     for(i in 1:nrow(pub.k)){
       cat(paste0(
         div(
          pub.k$authors[i], 
          paste0("(", pub.k$year[i], ") "),
          tags$b(pub.k$title[i]),
          tags$i(pub.k$item_info[i]),
          tags$a(pub.k$url_text[i], href = pub.k$url_text[i])
           )
         )
       )
     }
  }
  
  cat(paste0(br(), br()))
  }
```
